apiVersion: v1
kind: Service
metadata:
  name: intact-frontend
spec:
  selector:
    app: intact-frontend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intact-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intact-frontend
  template:
    metadata:
      labels:
        app: intact-frontend
    spec:
      containers:
        - name: frontend
          image: intact-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
